# Generated by Django 4.1.3 on 2022-11-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRAdmin",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="NormalStaff",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
        ),
        migrations.CreateModel(
            name="SalaryAdmin",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
        ),
    ]
