# Generated by Django 4.1.3 on 2022-11-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hradmin",
            options={
                "permissions": [
                    ("view_profile", "Can view profile"),
                    ("change_profile", "Can change profile"),
                    ("view_salary", "Can view salary"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="salaryadmin",
            options={
                "permissions": [
                    ("view_profile", "Can view profile"),
                    ("view_salary", "Can view salary"),
                    ("change_salary", "Can change salary"),
                    ("add_salary", "Can add salary"),
                ]
            },
        ),
    ]
