# Generated by Django 4.1.3 on 2022-11-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_hradmin_options_alter_salaryadmin_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="normalstaff",
            options={
                "permissions": [
                    ("view_profile", "Can view profile"),
                    ("view_salary", "Can view salary"),
                ]
            },
        ),
    ]
