# Generated by Django 4.1.3 on 2022-11-11 18:58

from django.db import migrations, models
import hr.validators


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_normalstaff_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="national_code",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                validators=[hr.validators.is_valid_iran_code],
                verbose_name="National code of User",
            ),
        ),
    ]
